micronaut:
  application:
    name: knowledge-app
  server:
    port: 8080
  router:
    static-resources:
      default:
        enabled: true
        mapping: /static/**
        paths: classpath:static

knowledge:
  default-password: ""

datasources:
  default:
    url: jdbc:h2:file:./knowledge-data;AUTO_SERVER=TRUE;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    schema-generate: NONE
    dialect: H2
